Rails.application.routes.draw do
  get 'users/create'
  get 'users/destroy'
  get 'users/edit'
  get 'users/index'
  get 'users/new'
  get 'users/show'
  get 'users/update'
  get 'gossips/create'
  get 'gossips/edit'
  get 'gossips/index'
  get 'gossips/new'
  get 'gossips/show'
  get 'gossips/update'
  get 'comments/create'
  get 'comments/destroy'
  get 'comments/edit'
  get 'comments/index'
  get 'comments/new'
  get 'comments/show'
  get 'comments/update'
  get 'cities/show'
  	get 'welcome/:user_name', to: 'welcome#user_name'
  	root 'home#gossip'
  	get '/static_pages/contact', to: 'static_pages#contact'
	get '/static_pages/team', to: 'static_pages#team'
end
